### ISSUE TITLE
Error on startup after upgrade to 1.0.5

### ISSUE THREAD

**Issue by andyparsons** [flask-admin/flask-admin#200]
We just upgraded from 1.0.4 to 1.0.5 and see this upon startup after the upgrade:

AttributeError: 'module' object has no attribute 'InputRequired'

The ModelView causing the failure looks like this:

``` python
class SignupLandingPagesView(ModelView):
    can_create = True
    can_delete = True
    page_size = 30

    def is_accessible(self):
        return (is_allowed('admin'))

    def __init__(self, session):
        super(SignupLandingPagesView, self).__init__(SignupLandingPage, session,
            name="Landing Pages", category="Onboarding")
```

Thanks for any guidance!
